sudo: false
os: linux
dist: trusty
language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly
addons:
    apt:
      packages:
      - openssl
      - pkg-config
      - zlib
matrix:
    allow_failures:
        - rust: nightly
          fast_finish: true

notifications:
  email:
    on_success: never
